:: This script is used to install liboqs, openssl, oqs-provider into a curl binary.

@ECHO OFF
ECHO Downloading liboqs (version 0.9.1)...

ECHO Downloading openssl (version 3.3.0 dev)...

ECHO Downloading oqs-provider (version 0.5.3)...